apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cloud-app.fullname" . }}-config
  labels:
    app: {{ .Release.Name }}
data:
  AWS_ENDPOINT_URL: {{ .Values.env.awsEndpointUrl | quote }}
  AWS_DEFAULT_REGION: {{ .Values.env.awsDefaultRegion | quote }}
  S3_BUCKET_NAME: {{ .Values.env.s3BucketName | quote }}
  DYNAMODB_TABLE_NAME: {{ .Values.env.dynamodbTableName | quote }}
  SQS_QUEUE_NAME: {{ .Values.env.sqsQueueName | quote }}
